name: homgingai
version: 1.0.0
slug: homgingai_homeassistant
description: homgingai Client/Server add-on for Home Assistant with support
url: https://github.com/aiakit/homgingai
boot: auto
init: false
host_network: true
homeassistant_api: true
panel_icon: mdi:robot-dead
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
map:
  - addons:rw
  - share:rw
  - media:rw
  - ssl:rw
  - addon_config:rw
  - homeassistant_config:rw  # 允许访问 Home Assistant 配置
options:
  phone:
  mail:
  speakers:
  openai_address:
  openai_key:
  openai_mode:
  filter_message:
schema:
  phone: str | None
  mail: str | None
  speakers: str | None
  openai_address: str | None
  openai_key: str | None
  openai_mode: str | None
  filter_message: str | None