name: homgingai
version: 1.0.0
slug: homgingai_homeassistant
description: homgingai Client/Server add-on for Home Assistant with support
url: https://github.com/aiakit/homgingai
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
host_network: true
init: false
map:
  - addons:rw
  - share:rw
options:
  phone: 手机号用于消息通知
  password: api密码，长度至少6位
  openai_key: openai密钥
  auth_token: homeassistant令牌
schema:
  phone: str
  password: str
  openai_key: str
  auth_token: str
