name: homgingai
version: 1.0.7
slug: homgingai_homeassistant
description: homgingai Client/Server add-on for Home Assistant with support
url: https://github.com/aiakit/homgingai
boot: auto
init: false
host_network: true
homeassistant_api: true
panel_icon: mdi:robot-dead
#ports:
#  8129/tcp: 8129
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
map:
  - addons:rw
  - share:rw
  - media:rw
  - ssl:rw
  - addon_config:rw
  - homeassistant_config:rw  # 允许访问 Home Assistant 配置
options:
  phone: ""
  mail: ""
  wake_up_mail: ""
  openai_address: ""
  openai_key: ""
  openai_mode: ""
  openai_fast_mode: ""
  filter_message: ""
  poetry: ""
  too_long: ""
  is_display: "1表示开启智能演示智能体，其他不开启"
  display_area: "演示区域选择"
schema:
  phone: str?
  mail: str?
  wake_up_mail: str?
  openai_address: str?
  openai_key: str?
  openai_mode: str?
  openai_fast_mode: str?
  filter_message: str?
  poetry: str?
  too_long: str?
  is_display: str?
  display_area: str?
